openapi: 3.0.0
info:
  title: Create Quote Lines from SAP Lines
  description: API to create quote lines in Heroku from SAP Install Line Items.
  version: 1.0.0
paths:
  /create-quote-lines-sap:
    post:
      summary: Create quote lines from SAP Install Line Items
      operationId: createQuoteLinesSAP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quoteId:
                  type: string
                  example: aPvOv000000jJphKAE
                sapLineIds:
                  type: array
                  items:
                    type: string
                  example: ["a1fa0000000Viv5AAC", "a1fa0000000Viv6AAC"]
                  x-sfdc:
                    heroku:
                      authorization:
                        connectedApp: 'HerokuQuoteLinesApp'
      responses:
        '200':
          description: Successfully created quote lines
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error